version: '3.8'

services:
  app:
    build: .
    container_name: trade-nb-members
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - trade-network

  nginx:
    image: nginx:alpine
    container_name: trade-nb-members-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - trade-network

networks:
  trade-network:
    driver: bridge

volumes:
  db_data:
  logs_data: 